MA-10585 [Android]u-boot: Fix build error "error: redefinition of 'init_csu'"
This build error in arch/arm/cpu/armv7/mx6/soc.c is introduced by mistake.

Change-Id: Ieecdc359bcd5a2eb60db4d96bcf06f19e8b2959f
Signed-off-by: Zhang Bo <bo.zhang@nxp.com>