MLK-18980 imx8mm_ddr4_val: fix build break for imx8mm_ddr4_val defconfig
The patch fixes the following build break by adding some missing definitons
into the defconfig

drivers/usb/gadget/f_sdp.c:278:59: error: ‘CONFIG_SDP_LOADADDR’
undeclared (first use in this function)
sdp->dnl_address = cmd->addr ? be32_to_cpu(cmd->addr):CONFIG_SDP_LOADADDR;
                                                           ^
make[3]: *** [spl/drivers/usb/gadget/f_sdp.o] Error 1

Signed-off-by: Jason Liu <jason.hui.liu@nxp.com>