MLK-15026-3 configs: imx8qm_arm2: enable USB3
Enable USB3 configuration, only host mode is supported now.
And disable EHCI support at imx8qm_lpddr4_arm2_defconfig.
Currently, the EHCI and xHCI can't be enabled at the same time
due to below redefinition symbols:

drivers/usb/host/xhci.o: In function `submit_control_msg':
/home/b29397/work/projects/uboot-imx/drivers/usb/host/xhci.c:1032: multiple definition of `submit_control_msg'
drivers/usb/host/ehci-hcd.o:/home/b29397/work/projects/uboot-imx/drivers/usb/host/ehci-hcd.c:1517: first defined here
drivers/usb/host/xhci.o: In function `submit_bulk_msg':
/home/b29397/work/projects/uboot-imx/drivers/usb/host/xhci.c:1045: multiple definition of `submit_bulk_msg'
drivers/usb/host/ehci-hcd.o:/home/b29397/work/projects/uboot-imx/drivers/usb/host/ehci-hcd.c:1141: first defined here
drivers/usb/host/xhci.o: In function `submit_int_msg':
/home/b29397/work/projects/uboot-imx/drivers/usb/host/xhci.c:1053: multiple definition of `submit_int_msg'
drivers/usb/host/ehci-hcd.o:/home/b29397/work/projects/uboot-imx/drivers/usb/host/ehci-hcd.c:1523: first defined here
drivers/usb/host/xhci.o: In function `usb_lowlevel_init':
/home/b29397/work/projects/uboot-imx/drivers/usb/host/xhci.c:1063: multiple definition of `usb_lowlevel_init'
drivers/usb/host/ehci-hcd.o:/home/b29397/work/projects/uboot-imx/drivers/usb/host/ehci-hcd.c:1097: first defined here
drivers/usb/host/xhci.o: In function `usb_lowlevel_stop':
/home/b29397/work/projects/uboot-imx/drivers/usb/host/xhci.c:1102: multiple definition of `usb_lowlevel_stop'
drivers/usb/host/ehci-hcd.o:/home/b29397/work/projects/uboot-imx/drivers/usb/host/ehci-hcd.c:1092: first defined here
scripts/Makefile.build:359: recipe for target 'drivers/usb/host/built-in.o' failed
make[1]: *** [drivers/usb/host/built-in.o] Error 1

If the user wants to use EHCI for chipidea IP at imx8qm, please comment out
CONFIG_USB_XHCI_HCD
CONFIG_USB_XHCI_IMX
And define
CONFIG_USB_EHCI_HCD
CONFIG_DM_USB
at imx8qm_lpddr4_arm2_defconfig

Signed-off-by: Peter Chen <peter.chen@nxp.com>