MLK-16729 tools: fix build break when libpython3-dev is installed
The u-boot meets break, when host build server has installed swig and libpython3-dev,
but no libpython-dev installed.

tools/libfdt_wrap.c:147:21: fatal error: Python.h: No such file or directory

The root cause is tools/makefile checks the Python.h before building a libfdt Python module.
Since the u-boot is using "python" command not "python3", we should change to check the Python.h
under python2.x directory not every python directory (like python3.x). Otherwise when a python3
develop package is installed, the script will get the file and start to build libfdt if swig
is installed as well.

Signed-off-by: Ye Li <ye.li@nxp.com>
Acked-by: Peng Fan <peng.fan@nxp.com>